# Generated by Django 5.2.1 on 2025-05-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifood_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ra',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
