# Generated by Django 4.2.21 on 2025-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unifood_app", "0005_item_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="eh_vendedor",
            field=models.IntegerField(default=0),
        ),
    ]
