name: Run Django Tests

on: push

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install Pipenv
          run: |
            python -m pip install --upgrade pip
            pip install pipenv

        - name: Install dependencies
          run: |
            pipenv install

        - name: Run Django tests
          run: |
            pipenv run cov

    deploy:
        runs-on: ubuntu-latest
        needs: tests
        if: success() && github.ref == 'refs/heads/prod'
        steps:

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            annotations: ${{ steps.meta.outputs.annotations }}
            provenance: true
            sbom: true

#        - name: Build Docker Image
#          run: |
#            docker build -f Containerfile -t unifood-image:latest .
#            docker tag unifood-image:latest ${{ secrets.DOCKER_USERNAME }}/unifood-image:latest
#
#        - name: Push Docker Image
#          run: |
#            docker push ${{ secrets.DOCKER_USERNAME }}/unifood-image:latest
#
#        - name: Deploying Image
#          run: |
#            echo "Deploying image...."