name: Run Django Tests

on: push

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install Pipenv
          run: |
            python -m pip install --upgrade pip
            pip install pipenv

        - name: Install dependencies
          run: |
            pipenv install

        - name: Run Django tests
          run: |
            pipenv run cov

    deploy:
        runs-on: ubuntu-latest
        needs: tests
        if: success() && github.ref == 'refs/heads/prod'
        steps:

        - name: Log in no Docker Hub
          run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Build Docker Image
          run: |
            docker build -f Containerfile -t unifood-image:latest .

        - name: Deploying Image
          run: |
            echo "Deploying image...."