name: Run Django Tests

on:
    push:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'  # Substitua pela versão do Python que você usa (ex.: '3.9')

        - name: Install Pipenv
          run: |
            python -m pip install --upgrade pip
            pip install pipenv

        - name: Install dependencies
          run: |
            pipenv install

        - name: Run Django tests
          run: |
            pipenv run cov