name: Run Django Tests

on: push

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install Pipenv
          run: |
            python -m pip install --upgrade pip
            pip install pipenv

        - name: Install dependencies
          run: |
            pipenv install

        - name: Run Django tests
          run: |
            pipenv run cov

    login:
      runs-on: ubuntu-latest
      steps:
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: dckr_pat_X-QNcSjehZ0EEiMCGJ8UOKv1ttw

    deploy:
        runs-on: ubuntu-latest
        needs: tests
        if: success() && github.ref == 'refs/heads/prod'
        steps:

        - name: Build Docker Image
          run: |
            docker build -f Containerfile -t unifood-image:latest .
            docker tag unifood-image:latest ViniCosta1/unifood-image:latest

        - name: Push Docker Image
          run: |
            docker push ViniCosta1/unifood-image:latest

        - name: Deploying Image
          run: |
            echo "Deploying image...."